# Generated by Django 5.2.1 on 2025-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(blank=True, max_length=200)),
                ('capa', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('Lido', 'Lido'), ('Lendo', 'Lendo'), ('Desejo ler', 'Desejo ler')], max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('data_leitura', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'google_id'), name='unique_user_googleid')
                ],
            },
        ),
    ]