# Generated by Django 5.2.1 on 2025-09-10 23:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='livrousuario',
            name='unique_user_livro',
        ),
        migrations.AlterUniqueTogether(
            name='livrousuario',
            unique_together={('user', 'livro')},
        ),
    ]
